pcr_params:
  # 일반 Primer 설계 설정
  primer_kwargs:
    min_amplicon_length: 80
    max_amplicon_length: 120
    n_primers: 10
    opt_length: 20
    min_length: 18
    max_length: 27
    opt_tm: 60.0
    min_tm: 55.0
    max_tm: 65.0
    opt_gc: 50.0
    min_gc: 40.0
    max_gc: 60.0
    # 추가 Primer3 옵션이 필요하면 여기에 작성
    primer3_global_args: {}

  # Probe 설계 설정
  probe_kwargs:
    n_probes: 10
    min_primer_probe_tm_diff: 5.0
    max_primer_probe_tm_diff: 10.0
    opt_length: 25
    min_length: 20
    max_length: 30
    opt_tm: 60.0
    min_tm: 60.0
    max_tm: 65.0
    opt_gc: 50.0
    min_gc: 40.0
    max_gc: 60.0

qc_criteria:
  # 1. 공통 열역학 기준 (Primer/Probe 공통)
  common_thermo:
    hairpin_max_dg: -5.0    # 이보다 낮으면(안정적이면) 탈락
    homodimer_max_dg: -6.0
    heterodimer_max_dg: -6.0

  # 2. 공통 Specificity 기준 (BLAST)
  common_specificity:
    identity_threshold: 90.0
    word_size: 12
    max_alignments: 50
    min_amp_len: 50
    max_amp_len: 300

  # 3. Primer 전용 기준
  primer:
    max_diff_tm: 3.0      # Fwd/Rev Tm 차이
    min_diff_tm: 0      # Fwd/Rev Tm 차이

  # 4. Probe 전용 기준
  probe:
    max_probe_3_end_gc: 3
    max_probe_poly_g: 3
    avoid_5_prime_g: true

  # [AS-PCR Criteria] AS-PCR 전용 QC 기준
  as_pcr_criteria:
    CHECK_3_PRIME_SPECIFICITY: true
