# pcr/designers/qpcr/config.yaml
# qPCR 전용 기본 설계 및 QC 파라미터

pcr_params:
  primer_kwargs:
    n_candidates: 3
    min_amplicon_length: 60
    max_amplicon_length: 150
    min_length: 20
    opt_length: 25
    max_length: 30
    min_tm: 45.0
    opt_tm: 55.0
    max_tm: 65.0
    min_gc: 35.0
    opt_gc: 50.0
    max_gc: 65.0

  probe_kwargs:
    n_candidates: 5
    min_length: 20
    opt_length: 25
    max_length: 30
    min_gc: 35.0
    opt_gc: 50.0
    max_gc: 65.0
    max_probe_poly_g: 3
    max_probe_3_end_gc: 2
    avoid_5_prime_g: true
    min_primer_probe_tm_diff: 5.0
    max_primer_probe_tm_diff: 10.0

qc_criteria:
  hairpin_min_dg: -5.0
  homodimer_min_dg: -6.0
  heterodimer_min_dg: -6.0
  min_identity: 90.0
  min_identity_threshold: 90.0
  min_hit_length: 13
  blast_max_alignments: 5
  min_amp_size: 50
  max_amp_size: 300
  primer:
    max_diff_tm: 3.0
  probe:
    min_primer_probe_tm_diff: 5.0
    max_primer_probe_tm_diff: 10.0