[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pcr-pipeline"
version = "0.1.0"
description = "Bioinformatics PCR Primer Design Pipeline"
authors = [{name = "Bioinfo Developer", email = "dev@bioinfo.com"}]
requires-python = ">=3.9"
dependencies = [
	"pydantic>=2.0",
	"primer3-py>=2.0",
	"pyyaml"
]

[tool.setuptools.packages.find]
where = ["src"]
