references:
  hg19:
    fasta_path: "/storage/references_and_index/hg19/fasta/cbNIPT/hg19.fa"
    blast_db_path: "/storage/home/jhkim/Apps/ncbi-blast-2.17.0+/ref/h19"
  hg38:
    fasta_path: "/storage/references_and_index/hg38/fasta/cbNIPT/hg38.fa"
    blast_db_path: "/storage/home/jhkim/Apps/ncbi-blast-2.17.0+/ref/hg38"

qc_tools:
  paths:
    blast_root: "/storage/home/jhkim/Apps/ncbi-blast-2.17.0+"
    blast_bin_dir: "/storage/home/jhkim/Apps/ncbi-blast-2.17.0+/bin"
    blastn: "/storage/home/jhkim/Apps/ncbi-blast-2.17.0+/bin/blastn"
    blastdbcmd: "/storage/home/jhkim/Apps/ncbi-blast-2.17.0+/bin/blastdbcmd"
    blast_db_path: "/storage/home/jhkim/Apps/ncbi-blast-2.17.0+/ref/hg38"
    blast_ref_path: "/storage/references_and_index/hg38/fasta/cbNIPT/hg38.fa"
