project:
  type: website
  output-dir: _site

website:
  navbar:
    background: "#0056b3" # 젠큐릭스 느낌의 블루 계열 (수정 가능)
    left:
      - href: main.qmd
        text: "Home"
      - href: qc/main.qmd
        text: "QC"
      - href: qpcr/main.qmd
        text: "qPCR"
      - href: as_pcr/main.qmd
        text: "AS-PCR"
      - href: ms_pcr/main.qmd
        text: "MS-PCR"
        
format:
  html:
    theme: cosmo
    css: static/css/styles.css
    toc: false
    page-layout: full
  