project:
  type: website
  output-dir: _site

website:
  title: "GENCURIX PRIMER SUITE"
  navbar:
    background: "#0056b3" # 젠큐릭스 느낌의 블루 계열 (수정 가능)
    left:
      - href: main.qmd
        text: "Home"
      - href: manual/main.qmd
        text: "Manual TaqMan qPCR"
      - href: qpcr/main.qmd
        text: "TaqMan qPCR"
      - href: as_pcr/main.qmd
        text: "Allele specific PCR (AS-PCR)"
      - href: ms_pcr/main.qmd
        text: "Methyl specific PCR (MS-PCR)"
        
format:
  html:
    theme: cosmo
    css: static/css/styles.css
    toc: false
    page-layout: full
  